version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000/
      - NEXTAUTH_SECRET='backendProjectFN132;'
      - NEXT_PUBLIC_REST_GO_EMAIL=restgo.booking@gmail.com
      - NEXT_PUBLIC_APP_PASSWORD=pnumeqvfdtdmhvcn
      - MONGO_URI=mongodb+srv://userRestGo:user06RestGo@cluster0.fsrvdia.mongodb.net/RestGo?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=RestGoSleep
      - JWT_EXPIRE=30d
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=userRestGo
      - MONGO_INITDB_ROOT_PASSWORD=user06RestGo

volumes:
  mongodb_data:
